src/component/history/history-component.jsx
src/component/history/history-container.js
src/component/history/history-list-component.jsx
src/component/history/history-list-container.jsx
src/component/history/history-list-toggle-component.jsx
src/store/index.js
src/store/settings/actions.js
src/store/settings/index.js

Implemented a settings-store backed by localstorage.

---

src/component/app.jsx
src/component/user/user-component.jsx
src/component/user/user-container.jsx
src/store/index.js
src/store/user/actions.js
src/store/user/index.js

The username-cookie is used by unleash server to show who changes what.
By making this a required input allow us to make sure
it is always set.
@sveisvei

Show a dialog if the username cookie is not set.

---

package.json
src/component/app.jsx
src/index.jsx

Keep scroll postion.

---

.babelrc
package.json
src/component/feature/form-add-container.jsx
src/component/feature/form-edit-container.jsx
src/component/feature/form/index.jsx
src/component/feature/form/strategies-list.jsx
src/component/feature/form/strategy-configure.jsx
src/component/input-helpers.js
src/jsconfig.json
src/store/input-actions.js
src/store/input-store.js
typings.json

Closes https://github.com/Unleash/unleash-frontend/issues/30
I did not add a hover-effect to the drop-target (yet)

Sort strategies

---

src/component/feature/feature-list-item-component.jsx
src/component/feature/feature.scss
src/component/feature/list-component.jsx

Added 100% width to feature link + some minor refactoring making use of mdl css classes.

make link to feature toggle span full width of list

---

src/component/feature/feature-list-item-component.jsx
src/component/feature/feature.scss

small chips

---

src/component/history/history-list-component.jsx

Render date as DD.MM.YYYY

---

src/.eslintrc
src/index.jsx
webpack.config.js

Should be tested before merge 😄 
https://github.com/zalmoxisus/redux-devtools-extension

Add redux dev tools in development

---

src/component/feature/feature-list-item-component.jsx
src/component/feature/feature.scss

Cuts back on some of the content to make more space for everything else.
@sveisvei Do you think we can combine this with regular chips as well, with regular font size and spacing?

summarize strategies for toggles with more than 3

---

src/component/app.jsx
src/component/common/common.scss
src/component/feature/metric-component.jsx
src/component/styles.scss
src/component/user/show-user-component.jsx

github link into menu + username tooltip + visual tweaks

---

src/component/app.jsx
src/component/styles.scss
src/index.jsx

removed Unleash from header title + visual tweaks

---

src/component/app.jsx
src/component/application/application-edit-component.js
src/component/application/application-list-component.js
src/component/archive/archive-list-component.jsx
src/component/common/common.scss
src/component/feature/feature-list-item-component.jsx
src/component/feature/feature.scss
src/component/feature/form/index.jsx
src/component/feature/list-component.jsx
src/component/feature/view-component.jsx
src/component/history/history-component.jsx
src/component/history/history-item-diff.jsx
src/component/history/history-list-component.jsx
src/component/strategies/add-strategy.jsx
src/component/strategies/list-component.jsx
src/component/strategies/strategy-details-component.jsx
src/component/styles.scss

This PR is a little all over the place, but it's all markup and styling changes. It's a foundation (#49) for further visual improvements on each individual component (eg. #50).
I also made the data tables scroll horizontally on small screens.

improved page layout + horizontal scrolling tables on mobile

---

src/component/feature/form-add-component.jsx
src/component/feature/form-add-container.jsx
src/component/feature/form/index.jsx

Another small preparation for #50 , just moving specific layout for the create feature toggle page into a separate component.

refactor layout into a new form add component

---

src/component/common/common.scss
src/component/feature/metric-component.jsx
src/component/feature/view-component.jsx

And heres the final layout change for the feature toggle page. Still more to do though, within each tab etc.
This closes #50 .
Before:
After:

changes layout for the feature toggle page

---

src/component/archive/archive-list-component.jsx
src/component/common/common.scss
src/component/history/history-list-component.jsx

Similar to the event history page.

adds a card layout and empty state styling to the archived toggles page

---

src/component/feature/list-component.jsx
src/component/feature/list-container.jsx

makes name default sorting

---

src/component/application/application-edit-component.js
src/component/application/application-list-component.js
src/component/common/index.js

Similar to feature list and view layouts. Just another item off the list :-)

minor improvements to application list and edit layouts

---

src/component/history/history-item-diff.jsx
src/component/history/history-list-component.jsx

Closes https://github.com/Unleash/unleash/issues/213

makes the history diff use all available space

---

src/component/app.jsx
src/index.jsx

Heading Should be Captialized

---

CHANGELOG.md
src/data/applications-api.js
src/data/archive-api.js
src/data/client-instance-api.js
src/data/feature-api.js
src/data/feature-metrics-api.js
src/data/history-api.js
src/data/strategy-api.js

https://github.com/Unleash/unleash/pull/227

Use updated routes from paths cleanup

---

src/component/strategies/list-component.jsx
src/component/strategies/strategy-details-component.jsx

* remove delete button for built-in strategies
* remove edit tab for built-in strategies

editable=false on strategies

---

CHANGELOG.md
src/component/application/__tests__/application-edit-component-test.js
src/component/application/application-edit-component.js
src/component/application/application-list-component.js
src/component/archive/archive-list-component.jsx
src/component/common/index.js
src/component/feature/form/index.jsx
src/component/feature/form/strategy-input-percentage.jsx
src/component/feature/list-component.jsx
src/component/feature/metric-component.jsx
src/component/history/history-component.jsx
src/component/history/history-list-component.jsx
src/component/history/history-list-toggle-component.jsx
src/component/strategies/add-strategy.jsx
src/component/strategies/list-component.jsx
src/component/user/show-user-component.jsx

:fire: :fireworks: :fire: :fire_engine: 
closes #21

chore(lint) Added propTypes to all components

---

src/component/feature/__tests__/__snapshots__/feature-list-item-component-test.jsx.snap
src/component/feature/feature-list-item-component.jsx
src/component/feature/form/__tests__/__snapshots__/form-update-feature-component-test.jsx.snap
src/component/feature/form/form-update-feature-component.jsx
src/component/feature/form/form-update-feature-container.jsx
src/component/feature/view-component.jsx

Fixes https://github.com/Unleash/unleash-frontend/issues/125

fix(feature): toggle correctly display for list and update feature

---

src/component/app.jsx
src/component/feature/list-component.jsx
src/component/feature/list-container.jsx
src/data/user-api.js
src/index.jsx
src/page/user/logout.js
src/store/user/actions.js

Fixed https://github.com/Unleash/unleash-frontend/issues/124

fix(signout): make signout works with proxy

---

src/component/feature/form/__tests__/__snapshots__/form-add-feature-component-test.jsx.snap
src/component/feature/form/form-add-feature-component.jsx

fix(feature): Create feature form inside a Card to align UI

---

src/component/error/error-container.jsx
src/component/feature/form/form-update-feature-container.jsx
src/store/error-store.js
src/store/feature-actions.js

feat(update-toggle): Do not change route after feature toggle update

---

src/component/feature/feature-list-item-component.jsx
src/component/feature/view-component.jsx
src/data/feature-api.js
src/store/feature-actions.js

See https://github.com/Unleash/unleash/pull/401

fix: Use toggle/on/off endoints to ensure correct state

---

src/component/feature/form/strategy-configure.jsx
src/component/strategies/add-strategy.jsx

See https://github.com/Unleash/unleash/issues/435 for details

feat: boolean strategy paramters

---

src/component/feature/form/__tests__/__snapshots__/form-update-feature-component-test.jsx.snap
src/component/feature/form/flexible-rollout-strategy-input.jsx
src/component/feature/form/form-update-feature-component.jsx
src/component/feature/form/select.jsx
src/component/feature/form/strategies-list.jsx
src/component/feature/form/strategies-section.jsx
src/component/feature/form/strategy-configure.jsx
src/component/feature/form/strategy-input-percentage.jsx
src/component/feature/form/strategy.scss
src/component/menu/header.jsx
src/data/context-api.js
src/store/context/actions.js
src/store/context/index.js
src/store/index.js

UI part of https://github.com/Unleash/unleash/issues/516

feat: Add support for strategy constraints.

---

src/component/feature/form/__tests__/__snapshots__/strategy-input-list-test.jsx.snap
src/component/feature/form/strategy-input-list.jsx

fix: Ensure chips are wrapped

---

src/component/common/index.js
src/component/common/util.js
src/component/context/create-context-container.js
src/component/context/edit-context-container.js
src/component/context/form-context-component.jsx
src/component/context/list-component.jsx
src/component/context/list-container.jsx
src/component/feature/variant/__tests__/__snapshots__/update-variant-component-test.jsx.snap
src/component/menu/__tests__/__snapshots__/routes-test.jsx.snap
src/component/menu/__tests__/routes-test.jsx
src/component/menu/routes.js
src/data/context-api.js
src/page/context/create.js
src/page/context/edit.js
src/page/context/index.js
src/permissions.js
src/store/context/actions.js
src/store/context/index.js
src/store/error-store.js
src/store/strategy/actions.js

feat: UI for view, create and edit context fields

---

src/data/user-api.js

The profile information is not updated correctly when you login with a username and password.

Transform username/password login response to json

---

src/store/application/index.js
src/store/archive-store.js
src/store/client-instance-store.js
src/store/context/index.js
src/store/feature-store.js
src/store/history-store.js
src/store/input-store.js
src/store/settings/index.js

fix: reset stores on login/logout

---

package.json
src/component/common/util.js
src/component/feature/variant/__tests__/__snapshots__/update-variant-component-test.jsx.snap
src/component/feature/variant/__tests__/update-variant-component-test.jsx
src/component/feature/variant/add-variant.jsx
src/component/feature/variant/enums.js
src/component/feature/variant/update-variant-component.jsx
src/component/feature/variant/variant-view-component.jsx
src/component/feature/variant/variant.scss

Variant List:
Variant Edit:
Variant Modal with Error:

Feat: (VariantCustomization) Allow user to customize variant weights

---

src/component/archive/view-container.js

Fix missing methods for displaying tags on archived toggles

---

src/component/feature/strategy/strategies-add.jsx
src/component/strategies/__tests__/__snapshots__/list-component-test.jsx.snap
src/component/strategies/__tests__/__snapshots__/strategy-details-component-test.jsx.snap
src/component/strategies/__tests__/list-component-test.jsx
src/component/strategies/list-component.jsx
src/component/strategies/list-container.jsx
src/component/strategies/show-strategy-component.js
src/component/strategies/strategies.module.scss
src/store/strategy/actions.js
src/store/strategy/api.js
src/store/strategy/index.js

This is not done yet, needs some work on the layout side. The functionality is in place though.

Basic implementation of deprecation/reactivation of strategies

---

src/component/feature/view/metric-component.jsx

fix: add missing space

---

src/store/feature-tags/index.js

fix: Use type and value from action to remove tag

---

src/component/menu/routes.js
src/page/admin/invoice/index.js
src/page/admin/invoice/invoice-container.js
src/page/admin/invoice/invoice-list.jsx
src/store/e-admin-invoice/actions.js
src/store/e-admin-invoice/api.js
src/store/e-admin-invoice/index.js
src/store/index.js
src/store/ui-config/__tests__/__snapshots__/ui-config-store.test.js.snap
src/store/ui-config/index.js

(sorry for not choosing typescript and new module format. need to spend some time learning the new setup)

feat: Add admin-invoice section

---

src/component/common/util.js
src/component/feature/FeatureToggleList/__tests__/__snapshots__/feature-list-item-component-test.jsx.snap
src/component/feature/create/CreateFeature/index.jsx
src/component/strategies/CreateStrategy/index.js

Fixes unleash/unleash#886
Based on #323 
Credits to @shanestillwell

Load name from url

---

src/component/feature/FeatureView2/FeatureLog/FeatureLog.tsx

remove semicolon from component

---

src/component/api-token/ApiTokenList/ApiTokenList.styles.ts
src/component/api-token/ApiTokenList/ApiTokenList.tsx
src/component/feature/FeatureToggleList/FeatureToggleListItem/styles.js
src/component/feature/FeatureToggleListNew/FeatureToggleListNew.styles.ts
src/component/strategies/StrategiesList/styles.js
src/page/admin/users/UsersList/UserListItem/UserListItem.styles.ts
src/page/admin/users/UsersList/UserListItem/UserListItem.tsx

https://www.loom.com/share/658105486a074fc8a71a1f959bffcd53

add highlight to table rows for features

---

src/component/menu/Footer/Footer.jsx
src/component/menu/__tests__/__snapshots__/footer-test.jsx.snap

fix: remove margin under footer

---

cypress/integration/feature-toggle/feature.spec.js
src/component/feature/FeatureView2/FeatureVariants/FeatureVariantsList/AddFeatureVariant/AddFeatureVariant.tsx
src/component/feature/FeatureView2/FeatureVariants/FeatureVariantsList/FeatureVariantsList.tsx
src/hooks/api/actions/useFeatureApi/useFeatureApi.ts

Co-authored-by: Fredrik Strand Oseberg <fredrik.no@gmail.com>

feat: Use new Variants API

---

src/component/feature/FeatureView2/FeatureVariants/FeatureVariantsList/FeatureVariantsListItem/FeatureVariantsListItem.tsx

- Fix an issue where clicking a variant in the list would popup a modal
dialog with empty details

Fix variant list

---

src/component/providers/SWRProvider/SWRProvider.tsx
src/hooks/api/getters/httpErrorResponseHandler.ts
src/hooks/api/getters/useUser/useUser.ts

Fix an issue in the SWR Provider where invalid token would cause the useUser hook to receive wrong data.

fix: account for invalid token in SWR Provider

---

src/component/feature/FeatureView2/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.styles.ts
src/component/feature/FeatureView2/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironmentFooter/FeatureOverviewEnvironmentFooter.tsx
src/component/feature/FeatureView2/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironmentMetrics/FeatureOverviewEnvironmentMetrics.styles.ts
src/component/feature/FeatureView2/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironmentMetrics/FeatureOverviewEnvironmentMetrics.tsx
src/component/feature/FeatureView2/FeatureStrategies/FeatureStrategyExecution/FeatureStrategyExecution.tsx

feat: update metrics view

---

src/component/feature/FeatureView2/FeatureStrategies/FeatureStrategiesEnvironments/FeatureStrategiesConfigure/FeatureStrategiesConfigure.tsx
src/component/feature/FeatureView2/FeatureStrategies/FeatureStrategiesEnvironments/FeatureStrategiesEnvironmentList/FeatureStrategiesEnvironmentList.tsx
src/component/feature/FeatureView2/FeatureStrategies/FeatureStrategiesEnvironments/FeatureStrategiesProductionGuard/FeatureStrategiesProductionGuard.tsx

https://www.loom.com/share/cc15a3b3884649d28c06a4dbe2f4059f

feat: add dont show again when update prod env

---

src/component/common/PaginateUI/PaginateUI.tsx
src/component/project/ProjectAccess/ProjectAccess.tsx

In this example, the pagination limit is 2, but the default that is used is `10`.

fix: add pagination to project access list

---

src/common.styles.js
src/component/admin/api-token/ConfirmToken/ConfirmToken.tsx
src/component/admin/api-token/ConfirmToken/UserToken/UserToken.tsx
src/component/admin/api-token/CreateApiToken/CreateApiToken.tsx

feat: show token after creation

---

src/component/common/Dialogue/Dialogue.tsx
src/component/common/EnvironmentStrategiesDialog/EnvironmentStrategyDialog.tsx
src/component/common/PermissionButton/PermissionButton.tsx
src/component/feature/FeatureView2/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironmentStrategies/FeatureOverviewEnvironmentStrategy/FeatureOverviewEnvironmentStrategy.tsx

https://www.loom.com/share/3903a92d376a4dbe87849a5369968b3c

feat: update dialog to accept permissions

---

package.json
src/component/application/application-list-component.js
src/component/application/application-list-container.js
yarn.lock

Simplifies the upcoming global settings refactor.

refactor: detach ApplicationList from global settings 

---

src/component/feature/FeatureView/FeatureStrategies/FeatureStrategiesEnvironments/FeatureStrategiesEnvironmentList/FeatureStrategiesEnvironmentList.tsx
src/component/feature/FeatureView/FeatureStrategies/FeatureStrategiesEnvironments/FeatureStrategiesEnvironmentList/useDropboxMarkup.tsx

https://www.loom.com/share/90ee832955934bb297db65e8be6bff6a

fix: clear query params when click cancel

---

package.json
yarn.lock

Also fixes this warning:
```
warning " > css-loader@6.6.0" has unmet peer dependency "webpack@^5.0.0".
```

refactor: remove unused deps

---

src/component/common/Constraint/Constraint.tsx
src/component/common/Constraint/formatConstraintValue.ts
src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditHeader/ConstraintAccordionEditHeader.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewBody/ConstraintAccordionViewBody.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ConstraintAccordionViewHeader.tsx
src/component/feature/FeatureStrategy/FeatureStrategyConstraints2/FeatureStrategyConstraints2.tsx

https://trello.com/c/nPnxAlYN/955-improve-constraint-date-formats

refactor: improve constraint date formatting 

---

src/component/common/Constraint/Constraint.styles.ts
src/component/common/ConstraintAccordion/ConstraintAccordion.styles.ts
src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/FreeTextInput/FreeTextInput.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewBody/ConstraintAccordionViewBody.tsx

https://trello.com/c/u9VQJQ89/956-improve-constraint-values-form

refactor: improve constraint values form

---

src/component/admin/apiToken/ApiTokenForm/SelectProjectInput/SelectAllButton/SelectAllButton.styles.ts
src/component/admin/apiToken/ApiTokenForm/SelectProjectInput/SelectAllButton/SelectAllButton.tsx
src/component/admin/apiToken/ApiTokenForm/SelectProjectInput/SelectProjectInput.test.tsx
src/component/admin/apiToken/ApiTokenForm/SelectProjectInput/SelectProjectInput.tsx

Adds tests and improvements to the form for creating API tokens.

Improve selecting projects

---

src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitch/FeatureOverviewEnvSwitch.tsx

For a few `@ts-expect-error`s less.

refactor: fix handling of unknown error

---

src/component/common/Table/TableCellSortable/TableCellSortable.styles.ts
src/component/common/Table/TableCellSortable/TableCellSortable.tsx

fix: users table sort header styles

---

src/component/feature/FeatureView/FeatureOverview/FeatureOverviewExecution/FeatureOverviewExecution.styles.ts
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewExecution/FeatureOverviewExecution.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewExecution/FeatureOverviewExecutionChips/FeatureOverviewExecutionChips.tsx
src/component/feature/StrategyTypes/StrategyInputList/StrategyInputList.tsx

Fixes https://github.com/Unleash/unleash-frontend/issues/917.

fix: truncate long parameter values

---

src/component/admin/users/UsersList/UserListItem/UserListItem.styles.ts
src/component/admin/users/UsersList/UserListItem/UserListItem.tsx
src/component/admin/users/UsersList/UsersList.tsx
src/component/common/Table/TableCellSortable/TableCellSortable.styles.ts
src/hooks/useUsersSort.ts

https://trello.com/c/sCvFqbnZ - UserList - add a column that displays when the user last logged in.

feat: add last seen col to admin users list

---

src/component/feedback/FeedbackCES/sendFeedbackInput.ts

This PR updates the target URL that the app sends feedback to. The function has been updated and moved to a different org, so the URL needs the update.

chore: Update target URL for sending feedback input

---

src/component/admin/projectRoles/EditProjectRole/EditProjectRole.tsx

Fixes an issue where renaming path parameter caused an error.

fix: path param

---

src/component/addons/AddonList/AddonList.tsx
src/component/addons/AddonList/ConfiguredAddons/ConfiguredAddons.tsx
src/component/admin/menu/AdminMenu.tsx
src/component/admin/projectRoles/ProjectRoles/ProjectRoleList/ProjectRoleList.tsx
src/component/admin/projectRoles/ProjectRoles/ProjectRoles.tsx
src/component/common/Table/cells/HighlightCell/HighlightCell.tsx
src/component/environments/EnvironmentActionCell/EnvironmentActionCell.tsx
src/component/environments/EnvironmentNameCell/EnvironmentNameCell.tsx

https://trello.com/c/l9FGX1kI
- `ProjectRoleList.tsx`
Also added a `HighlightCell` component, similar to `TextCell` but this one wraps the `Highlighter` component and only accepts `string` as either value or children.
Includes other misc improvements.

feat: Admin project roles table

---

src/component/menu/Header/Header.tsx

Fixes a bug that caused flags to be ignored when filtering admin routes, introduced in https://github.com/Unleash/unleash-frontend/pull/993
- `Header.tsx`

fix: admin routes bug

---

src/component/feature/FeatureView/FeatureVariants/FeatureVariantsList/PayloadOverridesCell/PayloadOverridesCell.tsx
src/component/project/Project/Project.tsx
src/component/project/ProjectAccess/ProjectAccess.tsx
src/component/project/ProjectAccess/ProjectAccessPage.tsx

https://trello.com/c/OilMJORC/1234-project-access-tab-gives-error-message-if-you-dont-have-permission-to-see-users
Fixes https://github.com/Unleash/unleash-frontend/issues/1051.

fix: disable project access tab when no access

---

src/component/common/ConstraintAccordion/ConstraintAccordion.styles.ts
src/component/common/ConstraintAccordion/ConstraintAccordionList/ConstraintAccordionList.styles.ts
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewBody/ConstraintAccordionViewBody.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ConstraintAccordionViewHeader.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewExecution/FeatureOverviewExecutionChips/FeatureOverviewExecutionChips.styles.ts
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSegment/FeatureOverviewSegment.styles.ts
src/component/project/ProjectCard/ProjectCard.styles.ts

fix: constraint-related UI fixes

---

package.json
src/component/admin/billing/BillingDashboard/BillingInformation/BillingInformationButton/BillingInformationButton.tsx

feat: add stripe integration

---

src/component/feature/CopyFeature/CopyFeature.tsx

fix: copy feature double validation popup

---

src/component/admin/users/UsersList/ChangePassword/ChangePassword.tsx
src/component/user/UserProfile/EditProfile/EditProfile.tsx
src/component/user/common/ResetPasswordForm/PasswordChecker/PasswordChecker.tsx

https://trello.com/c/R7ckzBUC/1327-password-update-for-user-owaspvalidationerror-no-details-on-frontend

refactor: improve password error handling

---

src/component/menu/Header/Header.tsx
src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
src/component/menu/routes.ts
src/component/playground/Playground/Playground.tsx
src/component/playground/Playground/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx
src/component/playground/Playground/PlaygroundConnectionFieldset/PlaygroundConnectionFieldset.tsx

Adds top part of UI for playground feature - for selecting environment and projects, and setting context.
`src/component/playground/Playground/Playground.tsx`

Playground form

---

src/component/addons/AddonForm/AddonForm.styles.tsx
src/component/addons/AddonForm/AddonForm.tsx
src/component/addons/AddonForm/AddonMultiSelector/AddonMultiSelector.tsx
src/component/addons/AddonForm/AddonParameters/AddonParameter/AddonParameter.tsx
src/component/addons/AddonForm/AddonParameters/AddonParameters.tsx

This PR updates the addon form to use the FormTemplate component to make the addon form align with the rest of our forms.

feat: Wrap addons form in FormTemplate

---

src/component/App.tsx
src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
src/component/menu/routes.ts
src/component/playground/Playground/LazyPlayground.tsx
src/component/playground/Playground/Playground.tsx

* Adds lazy loading for playground

feat: lazy load playground

---

src/component/common/StringTruncator/StringTruncator.tsx

Checks if we have a text before checking the length.

fix: truncator

---

src/component/admin/billing/Billing.tsx
src/component/admin/billing/BillingDashboard/BillingInformation/BillingInformation.tsx
src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
src/component/menu/routes.ts
src/hooks/api/getters/useInstanceStatus/useInstanceStatus.ts

Addresses some changes needed after internal evaluation and testing:
- Addresses should always be requested;
- Route title;
- Text changes;
- Leverage new `instance/refresh` endpoint for a better UX when signing up;

fix: pro flow stripe integration refinements

---

src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx
src/hooks/api/getters/useAccess/useAccess.ts
src/interfaces/group.ts

Added new endpoint that returns all users/groups with minimal fields.

Grouping access endpoint

---

src/component/admin/groups/Group/Group.tsx
src/component/admin/groups/GroupForm/GroupFormUsersTable/GroupFormUsersTable.tsx
src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx
src/component/admin/groups/GroupsList/GroupCard/GroupCardAvatars/GroupCardAvatars.tsx
src/component/admin/groups/GroupsList/GroupCard/GroupCardAvatars/GroupPopover/GroupPopover.tsx
src/component/admin/users/UsersList/ChangePassword/ChangePassword.tsx
src/component/admin/users/UsersList/DeleteUser/DeleteUser.tsx
src/component/admin/users/UsersList/UsersList.tsx
src/component/common/Badge/Badge.tsx
src/component/common/UserAvatar/UserAvatar.tsx
src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx
src/component/project/ProjectAccess/ProjectGroupView/ProjectGroupView.tsx

https://linear.app/unleash/issue/2-37/avatar-refactor-into-common-component
> Currently we have a lot of slightly different implementations/stylings of Avatar. Would be nice to refactor it into a common component to be used everywhere.
- `src/component/common/UserAvatar/UserAvatar.tsx`

refactor: create user avatar component, clean up

---

src/assets/icons/rollout.svg
src/component/common/ConstraintAccordion/ConstraintAccordion.styles.ts
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ConstraintViewHeaderOperator/ConstraintViewHeaderOperator.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ContraintAccordionViewHeaderMultipleValues/ConstraintAccordionViewHeaderMultipleValues.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ContraintAccordionViewHeaderSingleValue/ConstraintAccordionViewHeaderSingleValue.tsx
src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/StyledIconWrapper/StyledIconWrapper.tsx
src/component/common/ConstraintAccordion/ConstraintOperator/ConstraintOperator.styles.ts
src/component/common/ConstraintAccordion/ConstraintOperator/ConstraintOperator.tsx
src/component/common/EnvironmentIcon/EnvironmentIcon.tsx
src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx
src/component/feature/FeatureStrategy/FeatureStrategyEmpty/PresetCard/PresetCard.tsx
src/component/feature/FeatureStrategy/FeatureStrategyIcon/FeatureStrategyIcon.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyItem.styles.ts
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.styles.ts
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironmentMetrics/FeatureOverviewEnvironmentMetrics.tsx
src/utils/strategyNames.tsx

Updates to single feature view for constraints in strategies.

fix: minor UI improvements

---

src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx
src/component/feature/FeatureStrategy/FeatureStrategyEmpty/PresetCard/PresetCard.tsx

fix: add permission lock to quick strategy add

---

src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx

Small fix for project access assign checkboxes not being clickable.

fix: project access checkboxes

---

src/component/common/SegmentItem/SegmentItem.tsx
src/component/feature/FeatureStrategy/FeatureStrategySegment/FeatureStrategySegmentList.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyItem.tsx

Updated drag and drop of strategies on feature toggle page.
Closes [1-121](https://linear.app/unleash/issue/1-121/improve-drag-and-drop)
Relates to roadmap item: https://github.com/Unleash/unleash/issues/1879

Improve drag and drop on strategies

---

src/component/admin/groups/Group/RemoveGroupUser/RemoveGroupUser.tsx
src/component/admin/groups/RemoveGroup/RemoveGroup.tsx

Just some simple message updates

Update messages in the dialogs for groups

---

src/component/project/Project/DeleteProject/DeleteProjectDialogue.tsx
src/component/project/Project/Project.styles.ts
src/component/project/Project/Project.tsx
src/component/project/ProjectCard/ProjectCard.styles.ts
src/component/project/ProjectCard/ProjectCard.tsx

1. Added description to header
2. Added projectId to header
3. Added possiblity to delete project (Created reusable component)

New project page header

---

src/component/events/EventJson/EventJson.tsx

fix: wrap long lines in event JSON

---

src/component/feature/StrategyTypes/StrategyInputList/StrategyInputList.tsx

fix: wrap chips in feature strategy lists

---

src/component/admin/apiToken/ApiTokenDocs/ApiTokenDocs.tsx
src/component/admin/apiToken/ApiTokenForm/ApiTokenForm.styles.ts
src/component/admin/apiToken/ApiTokenForm/ApiTokenForm.tsx
src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
src/interfaces/uiConfig.ts

Add `FRONTEND` key type to the UI and update API access table.
Relates to roadmap item: https://github.com/Unleash/unleash/issues/1875

Feat: embedded proxy token

---

src/component/admin/apiToken/ApiTokenForm/ApiTokenForm.tsx
src/component/admin/cors/CorsForm.test.tsx
src/component/admin/cors/CorsForm.tsx
src/component/admin/cors/CorsHelpAlert.tsx
src/component/admin/cors/CorsTokenAlert.tsx
src/component/admin/cors/index.tsx
src/component/admin/menu/AdminMenu.tsx
src/component/common/util.ts
src/component/menu/Header/Header.tsx
src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
src/component/menu/routes.ts
src/hooks/api/actions/useUiConfigApi/useUiConfigApi.ts
src/interfaces/route.ts
src/interfaces/token.ts
src/interfaces/uiConfig.ts

https://linear.app/unleash/issue/1-171/embedded-proxy-instance-cors-settings-api
https://github.com/Unleash/unleash/issues/1875

feat: add CORS instance settings
