Unleash/unleash-frontend

- src/component/common/index.js
- src/component/feature/form/strategy-configure.jsx
- src/component/feature/form/strategy.scss
- src/component/feature/metric-component.jsx
- src/component/feature/metrics.scss
- src/component/feature/view-component.jsx
cc @ivarconr 
move some styles into stylesheet (ref #17 )
Added OR in edit view:
In metrics view:
_(When / if we add AND or other operators, the ui can just add a className for this on the element.)_
> Strategies in metrics view

- src/component/common/common.scss
- src/component/common/index.js
- src/component/feature/feature-list-item-component.jsx
- src/component/feature/feature.scss
- src/component/feature/list-component.jsx
- src/component/feature/list-container.jsx
- src/component/feature/metric-component.jsx
- src/component/feature/metric-container.jsx
Basically just moved the remove toggle button from feature list to view, retaining the original functionality. Maybe not the right place for it, though. Love to hear your thoughts on that.
Feature view desktop:
Feature view mobile:
> moved remove feature button from list to view

- src/component/application/application-edit-component.js
- src/component/common/util.js
- src/component/feature/view-component.jsx
- src/component/history/history-list-component.jsx
> Ensure the same date format everywhere

- src/component/feature/feature-list-item-component.jsx
- src/component/feature/form-add-container.jsx
- src/component/feature/form-edit-container.jsx
- src/component/feature/list-component.jsx
- src/component/feature/list-container.jsx
- src/component/feature/view-component.jsx
- src/data/feature-api.js
- src/store/feature-actions.js
- src/store/feature-store.js
Related to: https://github.com/Unleash/unleash/pull/199
* uses /toggle endpoint instead of posting whole feature json body
* cleans up strategy sort ids that leaked into the payload
cc @ivarconr
> use toggle-endpoint, cleanup strategy sort IDs

- src/component/common/common.scss
- src/component/common/index.js
- src/component/history/history-component.jsx
- src/component/history/history-list-component.jsx
- src/component/history/history-list-toggle-component.jsx
- src/component/history/history.scss
Preparation for #50 , but also relevant for #19 ?
Implements a data table header from the material design spec: https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards
A footer with pagination would also be nice :-)
Before:
After:
> added data table header component with title and actions

- src/component/feature/feature-list-item-component.jsx
- src/component/feature/feature.scss
- src/component/feature/metric-component.jsx
- src/component/feature/progress-styles.scss
- src/component/feature/progress.jsx
moved fallback icon into progress component, added a gauge icon, made styling more consistent
List before:
List after:
View before:
View after:
> adds a nicer fallback icon for metric progress

- src/component/strategies/add-strategy.jsx
This PR adds support for underscores in strategy names, allowing for const style naming conventions (`FOO_BAR`).
See related PR in `Unleash/unleash` - https://github.com/Unleash/unleash/pull/267
> Allow underscores in name validation

- src/component/app.jsx
the `sign out` appears only in the footer menu which does not make it very visible. This is a proposal to display it:
> fix(navigation): signout more visible

- src/component/feature/form/form-add-feature-container.jsx
- src/component/feature/form/strategies-list.jsx
- src/component/feature/form/strategies-section.jsx
Select the default strategy if the user has not added any strategies when creating new feature toggle. 
Closes https://github.com/Unleash/unleash/issues/204
> Default strategy is actually default. 

- src/component/history/history-list-component.jsx
- src/component/history/history-list-toggle-component.jsx
> Show tooltips and featuretoggle names in event history view

- .travis.yml
- CHANGELOG.md
- public/index.html
- src/component/api/__tests__/__snapshots__/show-api-details-component-test.jsx.snap
- src/component/api/__tests__/show-api-details-component-test.jsx
- src/component/api/show-api-details-component.jsx
- src/component/api/show-api-details-container.jsx
- src/component/app.jsx
- src/component/common/index.js
- src/component/feature/form/form-view-feature-component.jsx
- src/component/feature/form/strategy-configure.jsx
- src/component/feature/variant/update-variant-component.jsx
- src/component/history/history-container.js
- src/component/menu/__tests__/__snapshots__/drawer-test.jsx.snap
- src/component/menu/__tests__/__snapshots__/footer-test.jsx.snap
- src/component/menu/drawer.jsx
- src/component/menu/footer.jsx
- src/component/menu/header.jsx
- src/component/user/show-user-component.jsx
- src/component/user/show-user-container.jsx
- src/data/config-api.js
- src/index.jsx
- src/store/index.js
- src/store/ui-config/__tests__/__snapshots__/ui-config-store.test.js.snap
- src/store/ui-config/__tests__/ui-config-store.test.js
- src/store/ui-config/actions.js
- src/store/ui-config/index.js
This feature enables overrides of certain UI elements from the API, such as setting a different background color for the header. This could also solve #166 if we add a theme option. 
The idea is to make it easier to customise the UI, both for different environments, but also to provide company specific overrides (e.g. links to internal setup guides, etc) 
/cc @Kouzukii
> feat: Customisable UI via config

- src/component/feature/form/__tests__/__snapshots__/strategy-input-list-test.jsx.snap
- src/component/feature/form/strategy-input-list.jsx
**Issue**
When double-clicking on a chip, text belonging to a different chip also gets highlighted. After copying and pasting, any unwanted text then has to be removed manually.
**Affected browsers**
Only tested on Chrome 76
**Solution**
The proposed solution is to wrap chip span elements in a flex enabled div which will prevent multiple chip texts from getting highlighted after double-clicking. 
*Before*
Text selected after double-clicking the chip text: `cancel456`
The "cancel" bit comes from the close button description located in the previous chip in the list.
*After*
Text selected after double-clicking the chip text: `456`
> fix: Prevent text highlighting overlap between chips

- src/component/feature/__tests__/__snapshots__/view-component-test.jsx.snap
- src/component/feature/form/update-description-component.jsx
- src/component/feature/view-component.jsx
Currently it is always in edit mode which can be a bit confusing.
Usually one do not want to edit a toggle descirption and if one
do it should be OK to enter edit mode.
Now it alos stores changes in local state on the component so any
updates from the server should not affect the local value currently
beeing edited by the user.
fixes #168
> fix: Update feature toggle description.

- src/component/context/form-context-component.jsx
- src/component/feature/strategy/flexible-rollout-strategy-container.jsx
- src/component/feature/strategy/flexible-rollout-strategy.jsx
- src/component/feature/strategy/strategy-configure-component.jsx
- src/component/feature/variant/__tests__/__snapshots__/update-variant-component-test.jsx.snap
- src/component/feature/variant/__tests__/update-variant-component-test.jsx
- src/component/feature/variant/add-variant.jsx
- src/component/feature/variant/update-variant-component.jsx
- src/component/feature/variant/update-variant-container.jsx
- src/store/ui-config/__tests__/__snapshots__/ui-config-store.test.js.snap
- src/store/ui-config/index.js
The UI part for:
https://github.com/Unleash/unleash/pull/713
And:
https://github.com/Unleash/unleash-client-node/pull/201
How it looks:
And this allows more stickiness options on the flexible rollout:
And update variants with stickiness:
> feat: allow custom context fields to define stickiness.

- src/component/feature/view/metric-component.jsx
- src/store/feature-toggle/actions.js
- src/store/feature-toggle/api.js
Fixes an issue where createdAt field in the Metrics component showed: "Invalid date". The following steps have been done to prevent that from happening: 
- Added capabilities in unleash server to return the feature on create
- Added capabilities in unleash-frontend to receive the created feature and insert it into redux store.
> fix: metrics invalid date

- CHANGELOG.md
The link is broken as the reference `releases-url` doesn't exist, so I replaced it with what I think it's supposed to be.
> chore: fix releases URL in changelog

- src/component/user/common/ResetPasswordForm/PasswordChecker/PasswordChecker.styles.ts
- src/component/user/common/ResetPasswordForm/PasswordChecker/PasswordChecker.tsx
- src/component/user/common/ResetPasswordForm/ResetPasswordForm.tsx
Handles an obscure case in the password checker where password is not accepted because of three repeating characters. Now the user will receive a warning that three characters in a row is not permitted.
> fix: improve passwordchecker

- src/component/common/PasswordField/PasswordField.tsx
- src/component/user/PasswordAuth/PasswordAuth.jsx
> fix: add outlined for username login input and fix eye icon padding

- src/component/common/ListPlaceholder/ListPlaceholder.tsx
> fix: use correct path for create feature link

- src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/DateSingleValue/DateSingleValue.tsx
- src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/DateSingleValue/__tests__/__snapshots__/date-single-value-test.tsx.snap
- src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/DateSingleValue/__tests__/date-single-value-test.tsx
So we were using date-fn's format library with `kk` which handles hours as 01-24, instead of HH which is 00-23.
> fix: make sure we handle hours as 00-23

- src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditHeader/ConstraintAccordionEditHeader.tsx
Change the default date-based operator to DATE_AFTER instead of to DATE_BEFORE.
The reasoning is two-fold:
- I (we?) imagine it'll be more common to schedule a feature to be released _after_ a point in time, than to make it available _until_ some point in time.
- DATE_AFTER is the first item in the list, so it makes sense to use that as the default choice anyway
> feat: make DATE_AFTER the default time operator

- src/component/common/ConstraintAccordion/ConstraintOperatorSelect/ConstraintOperatorSelect.tsx
Fixes a case where we'd show a separator line above the first operator dropdown option.
> fix: remove separator from first option in list

- src/themes/app.css
Makes links match their parent by default.
> refactor: remove default link color

- src/hooks/useUsersFilter.ts
Downgrades the new user search to a basic text search, which should be more intuitive for end-users in most cases.
> fix: user search by text instead of regex

- package.json
- vite.config.ts
- yarn.lock
Cleaning up some small details after the Vite PR: https://github.com/Unleash/unleash-frontend/pull/940
- **package.json** - No longer has `react-scripts` as dependency;
- **vite.config.ts** - Now includes `server.open: true` (https://vitejs.dev/config/#server-open) so we can have the same behaviour as before - Opening the browser window automatically when running `start` locally;
> refactor: some cleanup after the vite PR

- src/component/addons/AddonForm/AddonForm.tsx
https://trello.com/c/Adl5O3Qm/1208-fe-cant-edit-addon-form-after-submitting-a-failed-form
> fix: avoid direct mutation of setState return value

- src/component/user/HostedAuth/HostedAuth.tsx
- src/component/user/PasswordAuth/PasswordAuth.tsx
- src/component/user/UserProfile/EditProfile/EditProfile.tsx
- src/component/user/common/ResetPasswordForm/ResetPasswordForm.tsx
Several inputs for username/password had invalid values for some attributes, namely `type` and `autocomplete`. These changes ensure that password managers are able to work correctly for these fields.
> Improve credential input attributes

- src/component/common/ToastRenderer/Toast/Toast.styles.ts
https://trello.com/c/nSzY9ekY/1338-long-string-name-needs-to-wrap-in-toast-messages
> fix: wrap long words in toast text

- src/component/common/PercentageCircle/PercentageCircle.tsx
- src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx
- src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx
- Fix a bug where it's not possible to edit a quickly added strategy, because of cached form data.
- Fix style of gradual rollout percentage indicator
> Fix: Refetch immutable toggle when adding strategy

- src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
- src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx
- src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyItem.tsx
- src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
On single feature page, adds a button with a menu that enables quick access to copying a strategy to another environment of the same toggle.
> Copy a strategy between environments

- package.json
- yarn.lock
* There seems to be a conflict in dependencies that causes an issue in the initialization of codemirror. This PR aims to remove unused deps that may conflict. 
See https://github.com/uiwjs/react-codemirror/issues/216
Related to: https://github.com/Unleash/unleash/issues/1873
> chore: remove unused codemirror deps
